version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: holdmybag
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app

volumes:
  db_data:
  redis_data: